#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_MENU_MAIN                           600
#define IDR_CONTEXT_MENU                        601
#define IDR_ACCEL                               602
#define IDR_POPUP_CHN                           610
#define IDR_POPUP_PST                           611
#define IDR_POPUP_REP                           612
#define IDR_POPUP_MOD                           613
#define IDR_POPUP_NET                           614
#define IDR_MENU_REPEDI                         615
#define IDR_MENU_MODEDI                         616
#define IDD_MGR                                 700
#define IDD_MGR_MAIN                            701
#define IDD_MGR_FOOT                            702
#define IDD_MGR_MAIN_LIB                        704
#define IDD_MGR_MAIN_NET                        705
#define IDD_MGR_MAIN_TST                        706
#define IDD_MGR_FOOT_OVW                        707
#define IDD_MGR_FOOT_DET                        708
#define IDD_MGR_FOOT_GAL                        709
#define IDD_ADD_CHN                             710
#define IDD_NEW_HUB                             711
#define IDD_ADD_PST                             712
#define IDD_ADD_REP                             713
#define IDD_TOOL_PKG                            714
#define IDD_TOOL_REP                            715
#define IDD_PROP_MGR                            720
#define IDD_PROP_MGR_GLE                        721
#define IDD_PROP_HUB                            722
#define IDD_PROP_HUB_CHN                        723
#define IDD_PROP_HUB_STG                        724
#define IDD_PROP_HUB_PST                        725
#define IDD_PROP_CHN                            726
#define IDD_PROP_CHN_STG                        727
#define IDD_PROP_CHN_LIB                        728
#define IDD_PROP_CHN_BCK                        729
#define IDD_PROP_CHN_NET                        730
#define IDD_PROP_PKG                            731
#define IDD_PROP_PKG_SRC                        732
#define IDD_PROP_PKG_BCK                        733
#define IDD_PROP_PKG_CMN                        734
#define IDD_PROP_RMT                            735
#define IDD_PROP_RMT_DET                        736
#define IDD_PROP_PST                            737
#define IDD_PROP_PST_STG                        738
#define IDD_PROP_PST_LST                        739
#define IDD_WIZ_HUB                             760
#define IDD_WIZ_HUB_BEG                         761
#define IDD_WIZ_HUB_CFG                         762
#define IDD_WIZ_CHN                             763
#define IDD_WIZ_CHN_BEG                         764
#define IDD_WIZ_CHN_TGT                         765
#define IDD_WIZ_CHN_CUS                         766
#define IDD_WIZ_REP                             767
#define IDD_WIZ_REP_BEG                         768
#define IDD_WIZ_REP_CFG                         769
#define IDD_WIZ_REP_QRY                         770
#define IDD_HELP_LOG                            780
#define IDD_HELP_ABT                            781
#define IDD_PICT_VIEW                           791
#define IDI_APP                                 800
#define IDI_ERR                                 801
#define IDI_WRN                                 802
#define IDI_NFO                                 803
#define IDI_QRY                                 804
#define IDI_PKG_ADD                             805
#define IDI_PKG_OWR                             806
#define IDI_PKG_WRN                             807
#define IDI_PKG_DEL                             808
#define IDI_PKG_ERR                             809
#define IDI_BT_ADD                              810
#define IDI_BT_REM                              811
#define IDI_BT_EDI                              812
#define IDI_BT_REF                              813
#define IDI_BT_DAD                              814
#define IDI_BT_FAD                              815
#define IDI_BT_FRM                              816
#define IDI_BT_ENT                              817
#define IDI_BT_NOT                              818
#define IDI_BT_OPN                              819
#define IDI_BT_NEW                              820
#define IDI_BT_WRN                              821
#define IDI_BT_UP                               822
#define IDI_BT_DN                               823
#define IDI_BT_RUN                              824
#define IDI_BT_SAV                              825
#define IDI_BT_SVD                              826
#define IDI_BT_SVA                              827
#define IDI_BT_IMP                              828
#define IDI_BT_VAL                              829
#define IDI_BT_ABT                              830
#define IDI_DEP_CHK                             835
#define IDI_PIC_ADD                             836
#define IDI_TXT_ADD                             837
#define IDI_PKG_IMP                             838
#define IDI_PKG_BLD                             839
#define IDI_CHN_ADD                             840
#define IDI_REP_ADD                             841
#define IDI_PST_ADD                             842
#define IDI_MOD_TOOL                            843
#define IDI_REP_TOOL                            844
#define IDI_DBG_LOG                             845
#define IDI_ABOUT                               846
#define IDI_CLOSE                               848
#define IDI_QUIT                                849
#define IDB_BLANK                               900
#define IDB_WIZARD                              901
#define IDB_ITM_PST                             904
#define IDB_ITM_PST_L                           905
#define IDB_ITM_CHN                             906
#define IDB_ITM_CHN_L                           907
#define IDB_ITM_REP                             908
#define IDB_ITM_REP_L                           909
#define IDB_ITM_MOD_ERR                         910
#define IDB_ITM_MOD_ERR_L                       911
#define IDB_ITM_MOD_DIR                         912
#define IDB_ITM_MOD_DIR_L                       913
#define IDB_ITM_MOD_PKG                         914
#define IDB_ITM_MOD_PKG_L                       915
#define IDB_ITM_MOD_DPN                         916
#define IDB_ITM_MOD_DPN_L                       917
#define IDB_STS_WIP                             918
#define IDB_STS_WIP_L                           919
#define IDB_STS_ERR                             920
#define IDB_STS_ERR_L                           921
#define IDB_STS_WRN                             922
#define IDB_STS_WRN_L                           923
#define IDB_STS_CHK                             924
#define IDB_STS_CHK_L                           925
#define IDB_STS_OVR                             926
#define IDB_STS_OVR_L                           927
#define IDB_STS_DNG                             928
#define IDB_STS_DNG_L                           929
#define IDB_STS_UPG                             930
#define IDB_STS_UPG_L                           931
#define IDB_STS_DNL                             932
#define IDB_STS_DNL_L                           933
#define IDB_STS_NEW                             934
#define IDB_STS_NEW_L                           935
#define IDB_STS_RES                             936
#define IDB_STS_RES_L                           937
#define IDB_STS_RB0                             938
#define IDB_STS_RB0_L                           939
#define IDB_STS_RB1                             940
#define IDB_STS_RB1_L                           941
#define IDB_STS_QUE                             942
#define IDB_STS_QUE_L                           943
#define IDB_DON_PP                              962
#define IDB_DON_PP_HOV                          963
#define IDB_SNAP_DIR                            990
#define IDB_SNAP_PKG                            991
#define IDC_SC_NAME                             40100
#define IDC_SC_HELP                             40101
#define IDC_SC_STATE                            40102
#define IDC_SC_NOTES                            40103
#define IDC_SC_MESG                             40104
#define IDC_SC_HEAD                             40105
#define IDC_SC_ITEM                             40106
#define IDC_SC_HTML                             40107
#define IDC_SC_WHITE                            40108
#define IDC_SC_LBL01                            40110
#define IDC_SC_LBL02                            40111
#define IDC_SC_LBL03                            40112
#define IDC_SC_LBL04                            40113
#define IDC_SC_LBL05                            40114
#define IDC_SC_LBL06                            40115
#define IDC_SC_LBL07                            40116
#define IDC_SC_LBL08                            40117
#define IDC_SC_LBL09                            40118
#define IDC_SC_LBL10                            40119
#define IDC_SC_LBL11                            40120
#define IDC_SC_FILE                             40121
#define IDC_SC_PATH                             40122
#define IDC_SC_INFO                             40123
#define IDC_SC_STATUS                           40190
#define IDC_SC_SEPAR                            40191
#define IDC_SC_SEP01                            40192
#define IDC_SC_SEP02                            40193
#define IDC_SC_SEP03                            40194
#define IDC_SC_STBAR                            40195
#define IDC_SC_VERS                             40196
#define IDC_SC_AUTH                             40197
#define IDC_SC_DATE                             40198
#define IDC_EC_INP01                            40200
#define IDC_EC_INP02                            40201
#define IDC_EC_INP03                            40202
#define IDC_EC_INP04                            40203
#define IDC_EC_INP05                            40204
#define IDC_EC_INP06                            40205
#define IDC_EC_INP07                            40206
#define IDC_EC_INP08                            40207
#define IDC_EC_INP09                            40208
#define IDC_EC_INP10                            40209
#define IDC_EC_RESUL                            40210
#define IDC_EC_READ1                            40211
#define IDC_EC_READ2                            40212
#define IDC_EC_READ3                            40213
#define IDC_EC_READ4                            40214
#define IDC_EC_READ5                            40215
#define IDC_EC_READ6                            40216
#define IDC_EC_READ7                            40217
#define IDC_EC_READ8                            40218
#define IDC_EC_READ9                            40219
#define IDC_EC_LISTE                            40220
#define IDC_EC_LIST1                            40221
#define IDC_EC_LIST2                            40222
#define IDC_EC_LIST3                            40223
#define IDC_EC_LIST4                            40224
#define IDC_EC_LIST5                            40225
#define IDC_EC_LIST6                            40226
#define IDC_EC_LIST7                            40227
#define IDC_EC_LIST8                            40228
#define IDC_EC_LIST9                            40229
#define IDC_EC_DESC                             40250
#define IDC_BC_BRW01                            40300
#define IDC_BC_BRW02                            40301
#define IDC_BC_BRW03                            40302
#define IDC_BC_BRW04                            40303
#define IDC_BC_BRW05                            40304
#define IDC_BC_BRW06                            40305
#define IDC_BC_BRW07                            40306
#define IDC_BC_BRW08                            40307
#define IDC_BC_BRW09                            40308
#define IDC_BC_BRW10                            40309
#define IDC_BC_SAVE                             40310
#define IDC_BC_SAV01                            40311
#define IDC_BC_SAV02                            40312
#define IDC_BC_SAV03                            40313
#define IDC_BC_LOAD                             40314
#define IDC_BC_OPEN                             40315
#define IDC_BC_OPEN2                            40316
#define IDC_BC_OPEN3                            40317
#define IDC_BC_INST                             40321
#define IDC_BC_UNIN                             40322
#define IDC_BC_DNLD                             40324
#define IDC_BC_SYNC                             40325
#define IDC_BC_DEL                              40330
#define IDC_BC_ADD                              40331
#define IDC_BC_EDI                              40332
#define IDC_BC_NEW                              40333
#define IDC_BC_ERASE                            40334
#define IDC_BC_RESET                            40335
#define IDC_BC_CHECK                            40336
#define IDC_BC_RIGH                             40340
#define IDC_BC_LEFT                             40341
#define IDC_BC_UP                               40342
#define IDC_BC_DN                               40343
#define IDC_BC_BACK                             40344
#define IDC_BC_NEXT                             40345
#define IDC_BC_DONATE                           40346
#define IDC_BC_APPLY                            40350
#define IDC_BC_OK                               40351
#define IDC_BC_IMPORT                           40352
#define IDC_BC_CANCEL                           40360
#define IDC_BC_ABORT                            40361
#define IDC_BC_CLOSE                            40362
#define IDC_BC_STOP                             40363
#define IDC_BC_CHADD                            40364
#define IDC_BC_CHDEL                            40365
#define IDC_BC_CHEDI                            40366
#define IDC_BC_PSNEW                            40367
#define IDC_BC_PSDEL                            40368
#define IDC_BC_PSEDI                            40369
#define IDC_BC_PSRUN                            40370
#define IDC_BC_RPQRY                            40371
#define IDC_BC_RPADD                            40372
#define IDC_BC_RPDEL                            40373
#define IDC_BC_DPADD                            40374
#define IDC_BC_DPDEL                            40375
#define IDC_BC_DPBRW                            40376
#define IDC_BC_DPVAL                            40377
#define IDC_BC_DPABT                            40378
#define IDC_TC_MAIN                             40400
#define IDC_TC_PROP                             40401
#define IDC_TC_HEAD                             40402
#define IDC_TB_TOOLS                            40409
#define IDC_CB_HUB                              40410
#define IDC_CB_CHN                              40411
#define IDC_CB_ZLV                              40412
#define IDC_CB_ICS                              40413
#define IDC_CB_EXT                              40414
#define IDC_CB_CAT                              40415
#define IDC_CB_ZMD                              40416
#define IDC_LB_PST                              40420
#define IDC_LB_PATH                             40421
#define IDC_LB_CHN                              40422
#define IDC_LB_DPN                              40423
#define IDC_LB_EXC                              40424
#define IDC_LB_INC                              40425
#define IDC_LB_REP                              40426
#define IDC_LB_MOD                              40427
#define IDC_LV_MOD                              40450
#define IDC_LV_NET                              40451
#define IDC_LV_PST                              40452
#define IDC_LV_REP                              40453
#define IDC_LV_INC                              40454
#define IDC_LV_EXC                              40455
#define IDC_LV_PAT                              40456
#define IDC_LV_CHN                              40457
#define IDC_LV_DPN                              40458
#define IDC_LV_IMG                              40459
#define IDC_PB_MOD                              40500
#define IDC_PB_REP                              40501
#define IDC_PB_COM                              40502
#define IDC_SB_ICON                             40600
#define IDC_SB_IMAGE                            40601
#define IDC_SB_SNAP                             40602
#define IDC_BC_CKBX1                            40700
#define IDC_BC_CKBX2                            40701
#define IDC_BC_CKBX3                            40702
#define IDC_BC_CKBX4                            40703
#define IDC_BC_CKBX5                            40704
#define IDC_BC_CKBX6                            40705
#define IDC_BC_CKBX7                            40706
#define IDC_BC_RAD01                            40710
#define IDC_BC_RAD02                            40711
#define IDC_LM_LNK01                            40720
#define IDC_LM_LNK02                            40721
#define IDC_GB_GRP01                            40730
#define IDC_GB_GRP02                            40731
#define IDC_GB_GRP03                            40732
#define IDC_GB_GRP04                            40733
#define IDC_GB_GRP05                            40734
#define IDC_GB_GRP06                            40735
#define IDC_GB_GRP07                            40736
#define IDC_GB_GRP08                            40737
#define IDC_GB_GRP09                            40738
#define IDC_GB_GRP10                            40739
#define IDC_FT_DESC                             40770
#define IDC_TB_CHN                              40780
#define IDC_TB_PST                              40781
#define IDC_TB_REP                              40782
#define IDM_BASE_ID                             40800
#define IDM_FILE_NEW                            40800
#define IDM_FILE_OPEN                           40810
#define IDM_FILE_CLOSE                          40811
#define IDM_FILE_CLEAR_HIST                     40812
#define IDM_FILE_SAVE                           40813
#define IDM_FILE_SAVAS                          40814
#define IDM_QUIT                                40815
#define IDM_MAN_PROP                            40820
#define IDM_HUB_PROP                            40821
#define IDM_CHN_ADD                             40822
#define IDM_CHN_DEL                             40823
#define IDM_CHN_PROP                            40824
#define IDM_PST_ADD                             40825
#define IDM_PST_RUN                             40826
#define IDM_PST_DEL                             40827
#define IDM_PST_PROP                            40828
#define IDM_REP_ADD                             40829
#define IDM_REP_QRY                             40830
#define IDM_REP_DEL                             40831
#define IDM_MOD_IMP                             40840
#define IDM_MOD_INST                            40841
#define IDM_MOD_UINS                            40842
#define IDM_MOD_CLNS                            40843
#define IDM_MOD_INFO                            40844
#define IDM_MOD_TRSH                            40845
#define IDM_MOD_OPEN                            40846
#define IDM_MOD_EDIT                            40847
#define IDM_MOD_DISC                            40848
#define IDM_MOD_BUIL                            40849
#define IDM_NET_DNWS                            40850
#define IDM_NET_DNLD                            40851
#define IDM_NET_FIXD                            40852
#define IDM_NET_INFO                            40853
#define IDM_NET_STOP                            40854
#define IDM_NET_RVOK                            40855
#define IDM_ENTRY_FADD                          40860
#define IDM_ENTRY_DADD                          40861
#define IDM_ENTRY_DEL                           40862
#define IDM_THMB_SEL                            40863
#define IDM_THMB_DEL                            40864
#define IDM_DESC_SEL                            40865
#define IDM_DEP_CHK                             40866
#define IDM_DEP_ADD                             40866
#define IDM_PKGEDITOR                           40880
#define IDM_REPEDITOR                           40881
#define IDM_DBGLOG                              40882
#define IDM_ABOUT                               40883
#define IDA_DEBUG_LOCK_MAN                      40890
#define IDA_DEBUG_LOCK_HUB                      40891
#define IDA_DEBUG_LOCKMODE                      40892
#define IDA_DEBUG_SAFEMODE                      40893
