#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_MENU                                600
#define IDR_ACCEL                               601
#define IDR_MENU_PST                            602
#define IDD_MGR                                 700
#define IDD_MGR_MAIN                            701
#define IDD_MGR_FOOT                            702
#define IDD_MGR_MAIN_LIB                        704
#define IDD_MGR_MAIN_NET                        705
#define IDD_MGR_MAIN_TST                        706
#define IDD_MGR_FOOT_OVW                        707
#define IDD_MGR_FOOT_DET                        708
#define IDD_MGR_FOOT_GAL                        709
#define IDD_ADD_CHN                             710
#define IDD_NEW_HUB                             711
#define IDD_ADD_PST                             712
#define IDD_ADD_REP                             713
#define IDD_TOOL_PKG                            714
#define IDD_TOOL_REP                            715
#define IDD_PROP_MGR                            720
#define IDD_PROP_MGR_GLE                        721
#define IDD_PROP_HUB                            730
#define IDD_PROP_HUB_CHN                        731
#define IDD_PROP_HUB_STG                        732
#define IDD_PROP_HUB_BAT                        733
#define IDD_PROP_CHN                            740
#define IDD_PROP_CHN_STG                        741
#define IDD_PROP_CHN_LIB                        742
#define IDD_PROP_CHN_BCK                        743
#define IDD_PROP_CHN_NET                        744
#define IDD_PROP_PKG                            750
#define IDD_PROP_PKG_SRC                        751
#define IDD_PROP_PKG_BCK                        752
#define IDD_PROP_PKG_CMN                        753
#define IDD_PROP_RMT                            755
#define IDD_PROP_RMT_DET                        756
#define IDD_PROP_PST                            760
#define IDD_PROP_PST_STG                        761
#define IDD_PROP_PST_LST                        762
#define IDD_WIZ_HUB                             770
#define IDD_WIZ_HUB_BEG                         771
#define IDD_WIZ_HUB_CFG                         772
#define IDD_WIZ_HUB_CHN                         773
//#define IDD_WIZ_CHN                             774
//#define IDD_WIZ_CHN_CFG                         775
#define IDD_HELP_LOG                            780
#define IDD_HELP_ABT                            781
#define IDD_PROGRESS                            790
#define IDD_PICT_VIEW                           791
#define IDI_APP                                 800
#define IDI_ERR                                 801
#define IDI_WRN                                 802
#define IDI_NFO                                 803
#define IDI_QRY                                 804
#define IDI_PKG_ADD                             805
#define IDI_PKG_OWR                             806
#define IDI_PKG_WRN                             807
#define IDI_PKG_DEL                             808
#define IDI_PKG_ERR                             809
#define IDI_BT_ADD                              810
#define IDI_BT_REM                              811
#define IDI_BT_MOD                              812
#define IDI_BT_REF                              813
#define IDI_BT_DAD                              814
#define IDI_BT_FAD                              815
#define IDI_BT_FRM                              816
#define IDI_BT_ENT                              817
#define IDI_BT_NOT                              818
#define IDI_BT_OPN                              819
#define IDI_BT_NEW                              820
#define IDI_BT_WRN                              821
#define IDI_BT_UP                               822
#define IDI_BT_DN                               823
#define IDI_BT_RUN                              824
#define IDB_BLANK                               900
#define IDB_WIZARD                              901
#define IDB_PKG_ERR_16                          910
#define IDB_PKG_ERR_24                          911
#define IDB_PKG_ERR_32                          912
#define IDB_PKG_DIR_16                          913
#define IDB_PKG_DIR_24                          914
#define IDB_PKG_DIR_32                          915
#define IDB_PKG_ZIP_16                          916
#define IDB_PKG_ZIP_24                          917
#define IDB_PKG_ZIP_32                          918
#define IDB_PKG_DPN_16                          919
#define IDB_PKG_DPN_24                          920
#define IDB_PKG_DPN_32                          921
#define IDB_STS_WIP_16                          922
#define IDB_STS_WIP_24                          923
#define IDB_STS_WIP_32                          924
#define IDB_STS_ERR_16                          925
#define IDB_STS_ERR_24                          926
#define IDB_STS_ERR_32                          927
#define IDB_STS_WRN_16                          928
#define IDB_STS_WRN_24                          929
#define IDB_STS_WRN_32                          930
#define IDB_STS_CHK_16                          931
#define IDB_STS_CHK_24                          932
#define IDB_STS_CHK_32                          933
#define IDB_STS_OVR_16                          934
#define IDB_STS_OVR_24                          935
#define IDB_STS_OVR_32                          936
#define IDB_STS_DNG_16                          937
#define IDB_STS_DNG_24                          938
#define IDB_STS_DNG_32                          939
#define IDB_STS_UPG_16                          940
#define IDB_STS_UPG_24                          941
#define IDB_STS_UPG_32                          942
#define IDB_STS_DNL_16                          943
#define IDB_STS_DNL_24                          944
#define IDB_STS_DNL_32                          945
#define IDB_STS_NEW_16                          946
#define IDB_STS_NEW_24                          947
#define IDB_STS_NEW_32                          948
#define IDB_STS_RES_16                          949
#define IDB_STS_RES_24                          950
#define IDB_STS_RES_32                          951
#define IDB_STS_RB0_16                          952
#define IDB_STS_RB0_24                          953
#define IDB_STS_RB0_32                          954
#define IDB_STS_RB1_16                          955
#define IDB_STS_RB1_24                          956
#define IDB_STS_RB1_32                          957
#define IDB_STS_QUE_16                          958
#define IDB_STS_QUE_24                          959
#define IDB_STS_QUE_32                          960
#define IDB_PST_16                              980
#define IDB_PST_24                              981
#define IDB_PST_32                              982
#define IDB_CHN_16                              983
#define IDB_CHN_24                              984
#define IDB_CHN_32                              985
#define IDB_REP_16                              986
#define IDB_REP_24                              987
#define IDB_REP_32                              988
#define IDB_SNAP_DIR                            990
#define IDB_SNAP_PKG                            991
#define IDC_SC_NAME                             40100
#define IDC_SC_INTRO                            40101
#define IDC_SC_STATE                            40102
#define IDC_SC_NOTES                            40103
#define IDC_SC_MESG                             40104
#define IDC_SC_HEAD                             40105
#define IDC_SC_ITEM                             40106
#define IDC_SC_HTML                             40107
#define IDC_SC_WHITE                            40108
#define IDC_SC_LBL01                            40110
#define IDC_SC_LBL02                            40111
#define IDC_SC_LBL03                            40112
#define IDC_SC_LBL04                            40113
#define IDC_SC_LBL05                            40114
#define IDC_SC_LBL06                            40115
#define IDC_SC_LBL07                            40116
#define IDC_SC_LBL08                            40117
#define IDC_SC_LBL09                            40118
#define IDC_SC_LBL10                            40119
#define IDC_SC_LBL11                            40120
#define IDC_SC_SEPAR                            40190
#define IDC_SC_SEP01                            40191
#define IDC_SC_SEP02                            40192
#define IDC_SC_SEP03                            40193
#define IDC_SC_SEP04                            40194
#define IDC_EC_INP01                            40200
#define IDC_EC_INP02                            40201
#define IDC_EC_INP03                            40202
#define IDC_EC_INP04                            40203
#define IDC_EC_INP05                            40204
#define IDC_EC_INP06                            40205
#define IDC_EC_INP07                            40206
#define IDC_EC_INP08                            40207
#define IDC_EC_INP09                            40208
#define IDC_EC_INP10                            40209
#define IDC_EC_RESUL                            40210
#define IDC_EC_READ1                            40211
#define IDC_EC_READ2                            40212
#define IDC_EC_READ3                            40213
#define IDC_EC_READ4                            40214
#define IDC_EC_READ5                            40215
#define IDC_EC_READ6                            40216
#define IDC_EC_READ7                            40217
#define IDC_EC_READ8                            40218
#define IDC_EC_READ9                            40219
#define IDC_EC_LISTE                            40220
#define IDC_EC_LIST1                            40221
#define IDC_EC_LIST2                            40222
#define IDC_EC_LIST3                            40223
#define IDC_EC_LIST4                            40224
#define IDC_EC_LIST5                            40225
#define IDC_EC_LIST6                            40226
#define IDC_EC_LIST7                            40227
#define IDC_EC_LIST8                            40228
#define IDC_EC_LIST9                            40229
#define IDC_EC_DESC                             40250
#define IDC_BC_BRW01                            40300
#define IDC_BC_BRW02                            40301
#define IDC_BC_BRW03                            40302
#define IDC_BC_BRW04                            40303
#define IDC_BC_BRW05                            40304
#define IDC_BC_BRW06                            40305
#define IDC_BC_BRW07                            40306
#define IDC_BC_BRW08                            40307
#define IDC_BC_BRW09                            40308
#define IDC_BC_BRW10                            40309
#define IDC_BC_SAVE                             40310
#define IDC_BC_SAV01                            40311
#define IDC_BC_SAV02                            40312
#define IDC_BC_SAV03                            40313
#define IDC_BC_LOAD                             40314
#define IDC_BC_OPEN1                            40315
#define IDC_BC_OPEN2                            40316
#define IDC_BC_OPEN3                            40317
#define IDC_BC_INST                             40321
#define IDC_BC_UNIN                             40322
#define IDC_BC_DNLD                             40324
#define IDC_BC_SYNC                             40325
#define IDC_BC_DEL                              40330
#define IDC_BC_ADD                              40331
#define IDC_BC_EDI                              40332
#define IDC_BC_NEW                              40333
#define IDC_BC_QRY                              40334
#define IDC_BC_REM                              40335
#define IDC_BC_RUN                              40336
#define IDC_BC_RIGH                             40340
#define IDC_BC_LEFT                             40341
#define IDC_BC_UP                               40342
#define IDC_BC_DN                               40343
#define IDC_BC_BACK                             40344
#define IDC_BC_NEXT                             40345
#define IDC_BC_APPLY                            40350
#define IDC_BC_OK                               40351
#define IDC_BC_CANCEL                           40360
#define IDC_BC_ABORT                            40361
#define IDC_BC_CLOSE                            40362
#define IDC_BC_STOP                             40363
#define IDC_BC_CHADD                            40364
#define IDC_BC_CHREM                            40365
#define IDC_BC_CHEDI                            40366
#define IDC_BC_PSNEW                            40367
#define IDC_BC_PSDEL                            40368
#define IDC_BC_PSEDI                            40369
#define IDC_BC_PSRUN                            40370
#define IDC_TC_MAIN                             40400
#define IDC_TC_PROP                             40401
#define IDC_TC_HEAD                             40402
#define IDC_CB_HUB                              40410
#define IDC_CB_CHN                              40411
#define IDC_CB_ZLV                              40412
#define IDC_CB_ICS                              40413
#define IDC_CB_EXT                              40414
#define IDC_CB_CAT                              40415
#define IDC_CB_ZMD                              40416
#define IDC_LB_PST                              40420
#define IDC_LB_PATH                             40421
#define IDC_LB_CHN                              40422
#define IDC_LB_DPN                              40423
#define IDC_LB_EXC                              40424
#define IDC_LB_INC                              40425
#define IDC_LB_REP                              40426
#define IDC_LB_PKG                              40427
#define IDC_LV_MOD                              40450
#define IDC_LV_NET                              40451
#define IDC_LV_PST                              40452
#define IDC_LV_REP                              40453
#define IDC_LV_INC                              40454
#define IDC_LV_EXC                              40455
#define IDC_LV_PAT                              40456
#define IDC_LV_CHN                              40457
#define IDC_LV_DPN                              40458
#define IDC_LV_IMG                              40459
#define IDC_PB_PKG                              40500
#define IDC_PB_REP                              40501
#define IDC_PB_COM                              40502
#define IDC_SB_ICON                             40600
#define IDC_SB_IMAGE                            40601
#define IDC_SB_SNAP                             40602
#define IDC_BC_CKBX1                            40700
#define IDC_BC_CKBX2                            40701
#define IDC_BC_CKBX3                            40702
#define IDC_BC_CKBX4                            40703
#define IDC_BC_CKBX5                            40704
#define IDC_BC_CKBX6                            40705
#define IDC_BC_CKBX7                            40706
#define IDC_BC_RAD01                            40710
#define IDC_BC_RAD02                            40711
#define IDC_LM_LNK01                            40720
#define IDC_LM_LNK02                            40721
#define IDC_GB_GRP01                            40730
#define IDC_GB_GRP02                            40731
#define IDC_GB_GRP03                            40732
#define IDC_GB_GRP04                            40733
#define IDC_GB_GRP05                            40734
#define IDC_GB_GRP06                            40735
#define IDC_GB_GRP07                            40736
#define IDC_GB_GRP08                            40737
#define IDC_GB_GRP09                            40738
#define IDC_GB_GRP10                            40739
#define IDC_FT_DESC                             40770
#define IDC_TB_CHN                              40780
#define IDC_TB_PST                              40781
#define IDC_TB_REP                              40782
#define IDM_BASE_ID                             40800
#define IDM_FILE_NEW_CTX                        40800
#define IDM_FILE_OPEN                           40810
#define IDM_FILE_CLOSE                          40811
#define IDM_FILE_CLEAR_HIST                     40812
#define IDM_FILE_QUIT                           40813
#define IDM_EDIT_OPTIONS                        40820
#define IDM_EDIT_CTX_PROP                       40821
#define IDM_EDIT_ADD_CHN                        40822
#define IDM_EDIT_CHN_PROP                       40823
#define IDM_EDIT_MOD_INST                       40830
#define IDM_EDIT_MOD_UINS                       40831
#define IDM_EDIT_MOD_CLNS                       40832
#define IDM_EDIT_MOD_INFO                       40833
#define IDM_EDIT_MOD_TRSH                       40834
#define IDM_EDIT_MOD_OPEN                       40835
#define IDM_EDIT_MOD_EDIT                       40836
#define IDM_EDIT_MOD_DISC                       40837
#define IDM_EDIT_NET_DNWS                       40840
#define IDM_EDIT_NET_DNLD                       40841
#define IDM_EDIT_NET_FIXD                       40842
#define IDM_EDIT_NET_INFO                       40843
#define IDM_EDIT_NET_STOP                       40844
#define IDM_EDIT_NET_RVOK                       40845
#define IDM_TOOLS_EDI_PKG                       40850
#define IDM_TOOLS_EDI_REP                       40851
#define IDM_HELP_LOG                            40860
#define IDM_HELP_ABOUT                          40861
#define IDM_PRESET_EXE                           40880
#define IDM_PRESET_EDI                           40881
#define IDM_PRESET_DEL                           40882
#define IDM_PRESET_NEW                           40883
