#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_MENU                                600
#define IDR_ACCEL                               601
#define IDD_MAIN                                700
#define IDD_MAIN_LIB                            701
#define IDD_MAIN_BAT                            702
#define IDD_NEW_LOC                             710
#define IDD_NEW_CTX                             711
#define IDD_NEW_PKG                             712
#define IDD_NEW_BAT                             713
#define IDD_PROP_MAN                            720
#define IDD_PROP_MAN_GLE                        721
#define IDD_PROP_MAN_PKG                        722
#define IDD_PROP_CTX                            730
#define IDD_PROP_CTX_LOC                        731
#define IDD_PROP_CTX_STG                        732
#define IDD_PROP_CTX_BAT                        733
#define IDD_PROP_LOC                            740
#define IDD_PROP_LOC_STG                        741
#define IDD_PROP_LOC_BCK                        742
#define IDD_PROP_PKG                            750
#define IDD_PROP_PKG_SRC                        751
#define IDD_PROP_PKG_BCK                        752
#define IDD_PROP_BAT                            760
#define IDD_PROP_BAT_STG                        761
#define IDD_WIZ_CTX                             770
#define IDD_WIZ_LOC                             771
#define IDD_WIZ_CTX_BEG                         774
#define IDD_WIZ_CTX_CFG                         775
#define IDD_WIZ_LOC_BEG                         776
#define IDD_WIZ_LOC_CFG                         777
#define IDD_HELP_LOG                            780
#define IDD_HELP_ABOUT                          781
#define IDD_PROGRESS                            790
#define IDB_APP_ICON                            800
#define IDB_WIZ_SPLASH                          801
#define IDB_PKG_ERR_16                          810
#define IDB_PKG_DIR_16                          811
#define IDB_PKG_ZIP_16                          812
#define IDB_PKG_DPN_16                          813
#define IDB_PKG_WIP_16                          814
#define IDB_PKG_BCK_16                          815
#define IDB_PKG_OWR_16                          816
#define IDB_PKG_ERR_24                          820
#define IDB_PKG_DIR_24                          821
#define IDB_PKG_ZIP_24                          822
#define IDB_PKG_DPN_24                          823
#define IDB_PKG_WIP_24                          824
#define IDB_PKG_BCK_24                          825
#define IDB_PKG_OWR_24                          826
#define IDB_PKG_ERR_32                          830
#define IDB_PKG_DIR_32                          831
#define IDB_PKG_ZIP_32                          832
#define IDB_PKG_DPN_32                          833
#define IDB_PKG_WIP_32                          834
#define IDB_PKG_BCK_32                          835
#define IDB_PKG_OWR_32                          836
#define IDB_BTN_ADD                             850
#define IDB_BTN_REM                             851
#define IDB_BTN_MOD                             852
#define IDB_BTN_UP                              860
#define IDB_BTN_DN                              861
#define IDB_PKG_BLANK                           870
#define IDC_EC_ENT03                            40000
#define IDC_EC_ENT04                            40001
#define IDC_SC_LBL06                            40002
#define IDC_EC_ENT06                            40003
#define IDC_SC_LBL07                            40004
#define IDC_SC_LBL08                            40005
#define IDC_EC_ENT02                            40006
#define IDC_SC_LBL05                            40007
#define IDC_EC_ENT05                            40008
#define IDC_EC_ENT07                            40009
#define IDC_EC_ENT08                            40010
#define IDC_SC_LBL09                            40011
#define IDC_SC_LBL10                            40012
#define IDC_SC_TEXT1                            40100
#define IDC_SC_TITLE                            40106
#define IDC_SC_DESC1                            40107
#define IDC_SC_LBL01                            40110
#define IDC_SC_LBL02                            40111
#define IDC_SC_LBL03                            40112
#define IDC_SC_LBL04                            40113
#define IDC_SC_SEPAR                            40190
#define IDC_SC_SEP01                            40191
#define IDC_SC_SEP02                            40192
#define IDC_SC_SEP03                            40193
#define IDC_SC_HEAD                             40195
#define IDC_EC_INPT1                            40200
#define IDC_EC_INPT2                            40201
#define IDC_EC_INPT3                            40202
#define IDC_EC_INPT4                            40203
#define IDC_EC_INPT5                            40204
#define IDC_EC_INPT6                            40205
#define IDC_EC_INPT7                            40206
#define IDC_EC_INPT8                            40207
#define IDC_EC_ENT01                            40210
#define IDC_EC_PKTXT                            40250
#define IDC_BC_BROW1                            40300
#define IDC_BC_BROW2                            40301
#define IDC_BC_BROW3                            40302
#define IDC_BC_BROW4                            40303
#define IDC_BC_BROW5                            40304
#define IDC_BC_SAVE                             40309
#define IDC_BC_INST                             40310
#define IDC_BC_UNIN                             40311
#define IDC_BC_LOAD                             40312
#define IDC_BC_DEL                              40315
#define IDC_BC_ADD                              40316
#define IDC_BC_EDIT                             40317
#define IDC_BC_NEW                              40318
#define IDC_BC_ABORT                            40320
#define IDC_BC_CLOSE                            40321
#define IDC_BC_UP                               40322
#define IDC_BC_DN                               40323
#define IDC_BC_BACK                             40330
#define IDC_BC_NEXT                             40331
#define IDC_BC_APPLY                            40340
#define IDC_BC_OK                               40341
#define IDC_BC_CANCEL                           40342
#define IDC_TC_MAIN                             40400
#define IDC_TC_PROP                             40401
#define IDC_CB_CTXLS                            40410
#define IDC_CB_LOCLS                            40411
#define IDC_CB_LEVEL                            40412
#define IDC_CB_ISIZE                            40413
#define IDC_LB_BATLS                            40420
#define IDC_LB_STRLS                            40421
#define IDC_LB_LOCLS                            40422
#define IDC_LB_DPNDS                            40423
#define IDC_LB_EXC                              40424
#define IDC_LB_INC                              40425
#define IDC_LV_PKGLS                            40450
#define IDC_LV_PSLST                            40451
#define IDC_PB_PGRES                            40500
#define IDC_SB_CTICO                           40600
#define IDC_SB_IMAGE                            40601
#define IDC_SB_PKIMG                            40602
#define IDC_BC_CHK01                            40700
#define IDC_BC_CHK02                            40701
#define IDC_BC_CHK03                            40702
#define IDC_BC_CHK04                            40703
#define IDC_BC_CHK05                            40704
#define IDC_BC_CHK06                            40705
#define IDC_BC_RAD01                            40710
#define IDC_BC_RAD02                            40711
#define IDC_LM_LNK01                            40720
#define IDC_LM_LNK02                            40721
#define IDM_FILE_NEW_CTX                        40800
#define IDM_FILE_NEW_PKG                        40802
#define IDM_FILE_OPEN                           40810
#define IDM_FILE_CLOSE                          40811
#define IDM_FILE_CLEAR_HIST                     40812
#define IDM_FILE_QUIT                           40813
#define IDM_EDIT_OPTIONS                        40820
#define IDM_EDIT_CTX_PROP                       40822
#define IDM_EDIT_CTX_ADDL                       40823
#define IDM_EDIT_PKG_INST                       40826
#define IDM_EDIT_PKG_UINS                       40827
#define IDM_EDIT_PKG_INFO                       40828
#define IDM_EDIT_PKG_TRSH                       40829
#define IDM_EDIT_PKG_OPEN                       40830
#define IDM_HELP_LOG                            40840
#define IDM_HELP_ABOUT                          40841
