#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_MENU                                600
#define IDR_ACCEL                               601
#define IDD_MAIN                                700
#define IDD_MAIN_LIB                            701
#define IDD_MAIN_NET                            702
#define IDD_ADD_LOC                             710
#define IDD_NEW_CTX                             711
#define IDD_ADD_BAT                             712
#define IDD_ADD_REP                             713
#define IDD_TOOL_PKG                            714
#define IDD_TOOL_REP                            715
#define IDD_PROP_MAN                            720
#define IDD_PROP_MAN_GLE                        721
#define IDD_PROP_MAN_PKG                        722
#define IDD_PROP_CTX                            730
#define IDD_PROP_CTX_LOC                        731
#define IDD_PROP_CTX_STG                        732
#define IDD_PROP_CTX_BAT                        733
#define IDD_PROP_LOC                            740
#define IDD_PROP_LOC_STG                        741
#define IDD_PROP_LOC_BCK                        742
#define IDD_PROP_LOC_NET                        743
#define IDD_PROP_PKG                            750
#define IDD_PROP_PKG_SRC                        751
#define IDD_PROP_PKG_BCK                        752
#define IDD_PROP_RMT                            755
#define IDD_PROP_RMT_DET                        756
#define IDD_PROP_BAT                            760
#define IDD_PROP_BAT_STG                        761
#define IDD_PROP_BAT_LST                        762
#define IDD_WIZ_CTX                             770
#define IDD_WIZ_CTX_BEG                         771
#define IDD_WIZ_CTX_CFG                         772
#define IDD_WIZ_CTX_LOC                         773
//#define IDD_WIZ_LOC                             774
//#define IDD_WIZ_LOC_CFG                         775
#define IDD_HELP_LOG                            780
#define IDD_HELP_ABT                            781
#define IDD_PROGRESS                            790
#define IDB_APP_ICON                            800
#define IDB_WIZ_SPLASH                          801
#define IDB_PKG_ERR_16                          810
#define IDB_PKG_ERR_24                          811
#define IDB_PKG_ERR_32                          812
#define IDB_PKG_DIR_16                          813
#define IDB_PKG_DIR_24                          814
#define IDB_PKG_DIR_32                          815
#define IDB_PKG_ZIP_16                          816
#define IDB_PKG_ZIP_24                          817
#define IDB_PKG_ZIP_32                          818
#define IDB_PKG_DPN_16                          819
#define IDB_PKG_DPN_24                          820
#define IDB_PKG_DPN_32                          821
#define IDB_STS_WIP_16                          822
#define IDB_STS_WIP_24                          823
#define IDB_STS_WIP_32                          824
#define IDB_STS_ERR_16                          825
#define IDB_STS_ERR_24                          826
#define IDB_STS_ERR_32                          827
#define IDB_STS_WRN_16                          828
#define IDB_STS_WRN_24                          829
#define IDB_STS_WRN_32                          830
#define IDB_STS_BOK_16                          831
#define IDB_STS_BOK_24                          832
#define IDB_STS_BOK_32                          833
#define IDB_STS_OWR_16                          834
#define IDB_STS_OWR_24                          835
#define IDB_STS_OWR_32                          836
#define IDB_STS_OLD_16                          837
#define IDB_STS_OLD_24                          838
#define IDB_STS_OLD_32                          839
#define IDB_STS_UPG_16                          840
#define IDB_STS_UPG_24                          841
#define IDB_STS_UPG_32                          842
#define IDB_STS_DNL_16                          843
#define IDB_STS_DNL_24                          844
#define IDB_STS_DNL_32                          845
#define IDB_BTN_ADD                             850
#define IDB_BTN_REM                             851
#define IDB_BTN_MOD                             852
#define IDB_BTN_REF                             853
#define IDB_BTN_DIR                             854
#define IDB_BTN_ENT                             855
#define IDB_BTN_NOT                             856
#define IDB_BTN_UP                              860
#define IDB_BTN_DN                              861
#define IDB_PKG_THN                             870
#define IDC_SC_TITLE                            40100
#define IDC_SC_INTRO                            40101
#define IDC_SC_STATE                            40102
#define IDC_SC_NOTES                            40103
#define IDC_SC_HEAD                             40104
#define IDC_SC_ITEM                             40105
#define IDC_SC_LBL01                            40110
#define IDC_SC_LBL02                            40111
#define IDC_SC_LBL03                            40112
#define IDC_SC_LBL04                            40113
#define IDC_SC_LBL05                            40114
#define IDC_SC_LBL06                            40115
#define IDC_SC_LBL07                            40116
#define IDC_SC_LBL08                            40117
#define IDC_SC_LBL09                            40118
#define IDC_SC_LBL10                            40119
#define IDC_SC_LBL11                            40120
#define IDC_SC_SEPAR                            40190
#define IDC_SC_SEP01                            40191
#define IDC_SC_SEP02                            40192
#define IDC_SC_SEP03                            40193
#define IDC_SC_SEP04                            40194
#define IDC_EC_INP01                            40200
#define IDC_EC_INP02                            40201
#define IDC_EC_INP03                            40202
#define IDC_EC_INP04                            40203
#define IDC_EC_INP05                            40204
#define IDC_EC_INP06                            40205
#define IDC_EC_INP07                            40206
#define IDC_EC_INP08                            40207
#define IDC_EC_INP09                            40208
#define IDC_EC_INP10                            40209
#define IDC_EC_OUT01                            40210
#define IDC_EC_OUT02                            40211
#define IDC_EC_OUT03                            40212
#define IDC_EC_OUT04                            40213
#define IDC_EC_OUT05                            40214
#define IDC_EC_OUT06                            40215
#define IDC_EC_OUT07                            40216
#define IDC_EC_OUT08                            40217
#define IDC_EC_OUT09                            40218
#define IDC_EC_OUT10                            40219
#define IDC_EC_PKTXT                            40250
#define IDC_BC_BRW01                            40300
#define IDC_BC_BRW02                            40301
#define IDC_BC_BRW03                            40302
#define IDC_BC_BRW04                            40303
#define IDC_BC_BRW05                            40304
#define IDC_BC_BRW06                            40305
#define IDC_BC_BRW07                            40306
#define IDC_BC_BRW08                            40307
#define IDC_BC_BRW09                            40308
#define IDC_BC_BRW10                            40309
#define IDC_BC_SAVE                             40310
#define IDC_BC_SAV01                            40311
#define IDC_BC_SAV02                            40312
#define IDC_BC_SAV03                            40313
#define IDC_BC_LOAD                             40314
#define IDC_BC_OPEN1                            40315
#define IDC_BC_OPEN2                            40316
#define IDC_BC_OPEN3                            40317
#define IDC_BC_INST                             40321
#define IDC_BC_UNIN                             40322
#define IDC_BC_UPGD                             40324
#define IDC_BC_SYNC                             40325
#define IDC_BC_DEL                              40330
#define IDC_BC_ADD                              40331
#define IDC_BC_EDI                              40332
#define IDC_BC_NEW                              40333
#define IDC_BC_CHK                              40334
#define IDC_BC_REM                              40335
#define IDC_BC_RUN                              40336
#define IDC_BC_RIGH                             40340
#define IDC_BC_LEFT                             40341
#define IDC_BC_UP                               40342
#define IDC_BC_DN                               40343
#define IDC_BC_BACK                             40344
#define IDC_BC_NEXT                             40345
#define IDC_BC_APPLY                            40350
#define IDC_BC_OK                               40351
#define IDC_BC_CANCEL                           40360
#define IDC_BC_ABORT                            40361
#define IDC_BC_CLOSE                            40362
#define IDC_BC_STOP                             40363
#define IDC_TC_MAIN                             40400
#define IDC_TC_PROP                             40401
#define IDC_TC_HEAD                             40402
#define IDC_CB_CTX                              40410
#define IDC_CB_LOC                              40411
#define IDC_CB_LVL                              40412
#define IDC_CB_ICS                              40413
#define IDC_CB_EXT                              40414
#define IDC_LB_BAT                              40420
#define IDC_LB_PATH                             40421
#define IDC_LB_LOC                              40422
#define IDC_LB_DPN                              40423
#define IDC_LB_EXC                              40424
#define IDC_LB_INC                              40425
#define IDC_LB_REP                              40426
#define IDC_LB_PKG                              40427
#define IDC_LV_PKG                              40450
#define IDC_LV_RMT                              40451
#define IDC_PB_PKG                              40500
#define IDC_PB_REP                              40501
#define IDC_PB_COM                              40502
#define IDC_SB_ICON                             40600
#define IDC_SB_IMAGE                            40601
#define IDC_SB_PKG                              40602
#define IDC_BC_CHK01                            40700
#define IDC_BC_CHK02                            40701
#define IDC_BC_CHK03                            40702
#define IDC_BC_CHK04                            40703
#define IDC_BC_CHK05                            40704
#define IDC_BC_CHK06                            40705
#define IDC_BC_RAD01                            40710
#define IDC_BC_RAD02                            40711
#define IDC_LM_LNK01                            40720
#define IDC_LM_LNK02                            40721
#define IDC_GB_GRP01                            40730
#define IDC_GB_GRP02                            40731
#define IDC_GB_GRP03                            40732
#define IDC_GB_GRP04                            40733
#define IDC_GB_GRP05                            40734
#define IDC_GB_GRP06                            40735
#define IDC_GB_GRP07                            40736
#define IDC_GB_GRP08                            40737
#define IDC_GB_GRP09                            40738
#define IDC_GB_GRP10                            40739
#define IDM_BASE_ID                             40800
#define IDM_FILE_NEW_CTX                        40800
#define IDM_FILE_OPEN                           40810
#define IDM_FILE_CLOSE                          40811
#define IDM_FILE_CLEAR_HIST                     40812
#define IDM_FILE_QUIT                           40813
#define IDM_EDIT_OPTIONS                        40820
#define IDM_EDIT_CTX_PROP                       40821
#define IDM_EDIT_ADD_LOC                        40822
#define IDM_EDIT_LOC_PROP                       40823
#define IDM_EDIT_PKG_INST                       40824
#define IDM_EDIT_PKG_UINS                       40825
#define IDM_EDIT_PKG_INFO                       40826
#define IDM_EDIT_PKG_TRSH                       40827
#define IDM_EDIT_PKG_OPEN                       40828
#define IDM_EDIT_RMT_DOWN                       40830
#define IDM_EDIT_RMT_UPGR                       40831
#define IDM_EDIT_RMT_FIXD                       40832
#define IDM_EDIT_RMT_INFO                       40833
#define IDM_TOOLS_EDI_PKG                       40850
#define IDM_TOOLS_EDI_REP                       40851
#define IDM_HELP_LOG                            40860
#define IDM_HELP_ABOUT                          40861
